### ISSUE TITLE
How to build a pandas dataframe from Semi_ATE.STDF.utils.records_from_file

### ISSUE THREAD

**Issue by danielhaviv** [Semi-ATE/STDF#35] opened 2021-11-11 13:59 UTC
Hi,
Is there a suggested way I can easily read a STDF file (or transfrom Semi_ATE.STDF.utils.records_from_file) into a pandas dataframe?

**Comment by csoltenborn** [comment] 2021-11-12 12:22
In fact, that's pretty much also my question - nice coincidence  :-)

**Comment by seimit** [comment] 2021-11-12 16:38
Hello Daniel
I made a tool stdf2ph5.py in the Semi-ATE's Metis project:
https://github.com/Semi-ATE/Metis/tree/main/Metis/tools
The tool will parse the STDF file and will write pandas dataframe in HDF5 file.
I do not had time to tested fully. There is some preliminary documentation in the documentation folder. 
I will try my best to update the doc and to give example how to use the tools.
Let me know if there is an issues.
Also there is stdf to csv file convertor as well.
Regards,
Seimit

**Comment by csoltenborn** [comment] 2021-11-19 09:29
@seimit Thanks a lot for your prompt response! I only now had time to look into this. As a side note, I'm trying to evaluate options to convert STDF to CSV, and to figure out how much information loss would result from such a conversion. For this, I'm trying to use the [attached file](https://github.com/Semi-ATE/STDF/files/7569183/STDF.zip) (which I found [here](https://github.com/showjim/STDFReader/tree/a2aa661be78df8de658255880c0dc863aab18ee0)). However, running your conversion tool results in the following output:

```
C:\Users\chris\git\Metis\venv\Scripts\python.exe C:/Users/chris/git/Metis/Metis/tools/stdf2csv.py -i C:\Users\chris\git\Metis\STDF.stdf -o C:\Users\chris\git\Metis\conversion_result -d

Tool for converting STDF binary files into CSV files.
Debug is enabled
ERROR : Can not decode FAR record. Make sure the file is not compressed : C:\Users\chris\git\Metis\STDF.stdf
```

The file (the one within the zip file ;-)) does not look like it's compressed to me (since opening it in an editor shows a lot of readable strings) - any idea what the problem is? Does the file contain constructs which are not supported by Semi_ATE?

**Comment by seimit** [comment] 2021-11-21 18:23
@csoltenborn Thanks for reporting this! I will fix it in the next minutes.

**Comment by seimit** [comment] 2021-11-21 18:45
Hi csoltenborn 
I fixed the original problem, but there is exception after FAR record processing.
Because it is too late now for me, I will fix it next week, may be Thursday/Friday.

**Comment by seimit** [comment] 2021-11-25 19:29
Hi
The issue with reading STDF file was fixed.
Could you try now?
Regards,
Seimit

**Comment by csoltenborn** [comment] 2021-11-26 05:47
Thanks a lot! :-)

I will try probably today and let you know...

**Comment by Mike-Purtell** [comment] 2021-11-30 19:14
Easiest (and fastest I think) to put stdf records into a dataframe  is to follow these steps:

1) create an empty list, and iterate over all records in the stdf file. 
stdf_dictionary_list =[] 
for REC in STDF.records_from_file(StdfFileName):

2) convert each record to a python dictionary.  Recommend a filter to only include specific RECORD types,  for example if REC.id == 'PTR': 
stdf_dictionary_list.append(REC.to_dict())  #you can use a filter to only add specific record types

3) create your dataframe as shown here: 
df_stdf = pd.DataFrame(stdf_dict_list)

works very well for me and quite fast.   I use the stdf dictionary for PTR, MPR, FTR, and PRR.  For HBR, SBR, and MRR, I just add them to dedicated lists for each record type, and parse them to make summaries.  This work from SEMI-ATE is very good and I am so happy to have found it.

**Comment by seimit** [comment] 2021-12-01 20:02
Hi Mike,
Thanks for the tip!
I think is time to close this issue.
Thanks to all of you!
Best Regards,
Seimit

**Closed by seimit** 2021-12-01 20:02 UTC

**Comment by csoltenborn** [comment] 2021-12-02 08:39
@seimit Sorry for being late to the party - I finally tried your change, and it works like a charm now. Thanks once more! :-)

@Mike-Purtell Very helpful - thanks a lot!
