### ISSUE TITLE
Unable to parser SDR records

### ISSUE THREAD

**Issue by hcyang0207** [Semi-ATE/STDF#31] opened 2021-10-29 04:05 UTC
### Tasks/Steps/Elements
code:
```
stdf_file = STDF.records_from_file("cde.stdf")
for REC in stdf_file:
	if REC is not None:
		print(REC.id)
	else:
		stdf_dict = REC.__repr__()
		print(stdf_dict)
```

result:
```
FAR
MIR
None   <--- SDR Read None
TSR
TSR
TSR
```
Unable to parser SDR records.

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by seimit** [comment] 2021-11-02 18:22
Duplicate of #29 
I just released 0.1.17 which includes the fix of the issue (now available in pypi, later in conda).
Sorry for the late answer!
Best Regards,
Seimit

**Closed** 2021-11-02 18:22 UTC
